import type { SpecVersionHeader } from "./types.js";

const SPEC_VERSION = 1;
const GENERATOR_VERSION = "0.1.0";

export function buildSpecVersionHeader(opts: Omit<SpecVersionHeader, "version" | "generated" | "specVersion">): string {
  return [
    `// @generated by TestMind`,
    `// version: ${GENERATOR_VERSION}`,
    `// generated: ${new Date().toISOString()}`,
    `// target: ${opts.target}`,
    ...(opts.framework ? [`// framework: ${opts.framework}`] : []),
    ...(opts.confidence !== undefined ? [`// confidence: ${opts.confidence}`] : []),
    ...(opts.crawlDepth !== undefined ? [`// crawlDepth: ${opts.crawlDepth}`] : []),
    `// specVersion: ${SPEC_VERSION}`,
    ``,
  ].join("\n");
}

export function injectSpecHeader(content: string, opts: Omit<SpecVersionHeader, "version" | "generated" | "specVersion">): string {
  const header = buildSpecVersionHeader(opts);
  // Don't double-inject
  if (content.trimStart().startsWith("// @generated by TestMind")) return content;
  return header + content;
}
