import { createHash } from "node:crypto";

export function crawlFingerprint(metadata) {
  const stable = JSON.stringify({
    routes: [...metadata.routes].sort(),
    forms: metadata.forms
      .map((f) => `${f.action}:${f.method}:${[...f.fields].sort().join(",")}`)
      .sort(),
    apis: [...metadata.apis].sort(),
  });
  return createHash("sha256").update(stable).digest("hex").slice(0, 16);
}

const SPEC_VERSION = 1;
const GENERATOR_VERSION = "0.1.0";

export function buildSpecVersionHeader(opts) {
  return [
    `// @generated by TestMind`,
    `// version: ${GENERATOR_VERSION}`,
    `// generated: ${new Date().toISOString()}`,
    `// target: ${opts.target}`,
    ...(opts.framework ? [`// framework: ${opts.framework}`] : []),
    ...(opts.confidence !== undefined ? [`// confidence: ${opts.confidence}`] : []),
    ...(opts.crawlDepth !== undefined ? [`// crawlDepth: ${opts.crawlDepth}`] : []),
    `// specVersion: ${SPEC_VERSION}`,
    ``,
  ].join("\n");
}

export function injectSpecHeader(content, opts) {
  const header = buildSpecVersionHeader(opts);
  if (content.trimStart().startsWith("// @generated by TestMind")) return content;
  return header + content;
}
