import OpenAI from "openai";
import { Octokit } from "@octokit/rest";
import { createAppAuth } from "@octokit/auth-app";
import fs from "node:fs/promises";
import { exec as cpExec } from "node:child_process";
import { promisify } from "node:util";
import { generateAndWrite } from "../../src/testmind/service.js";
import path from "node:path";
import { GENERATED_ROOT, ensureStorageDirs } from "../lib/storageRoots.js";
import { DEFAULT_FRAMEWORK_ID } from "@testmind/core/framework";

const exec = promisify(cpExec);

function parseSharedStepsEnv(): Record<string, unknown> | undefined {
  const raw = process.env.TM_PROJECT_SHARED_STEPS;
  if (!raw) return undefined;
  try {
    return JSON.parse(raw) as Record<string, unknown>;
  } catch (err) {
    console.warn("[runner] failed to parse TM_PROJECT_SHARED_STEPS", err);
    return undefined;
  }
}

async function getOctokit(): Promise<Octokit> {
  const {
    GITHUB_TOKEN,
    GITHUB_APP_ID,
    GITHUB_APP_INSTALLATION_ID,
    GITHUB_APP_PRIVATE_KEY_BASE64,
  } = process.env;

  if (GITHUB_APP_ID && GITHUB_APP_INSTALLATION_ID && GITHUB_APP_PRIVATE_KEY_BASE64) {
    const privateKey = Buffer.from(GITHUB_APP_PRIVATE_KEY_BASE64, "base64").toString("utf8");
    const auth = createAppAuth({
      appId: Number(GITHUB_APP_ID),
      privateKey,
      installationId: Number(GITHUB_APP_INSTALLATION_ID),
    });
    const { token } = await auth({ type: "installation" });
    return new Octokit({ auth: token });
  }

  if (!GITHUB_TOKEN) throw new Error("No GitHub auth found (set GITHUB_TOKEN or App creds).");
  return new Octokit({ auth: GITHUB_TOKEN });
}

async function comment(octokit: Octokit, repoRef: { owner: string; repo: string }, issue_number: number, body: string) {
  await octokit.issues.createComment({ ...repoRef, issue_number, body });
}

async function main() {
  const {
    GITHUB_REPOSITORY = "",
    GITHUB_EVENT_NAME = "",
    GITHUB_EVENT_PATH = "",
    OPENAI_API_KEY = "",
    LOCAL_RUN = "",
  } = process.env;

  const localMode = LOCAL_RUN === "1";
  // This bot path remains Playwright-only until the CI/bot flow is moved under the framework layer.
  const adapterId = DEFAULT_FRAMEWORK_ID;
  // TM_GENERATED_OUT_ROOT (set by startGeneratedRun) scopes output to a single
  // project. Without it, this fell back to a flat GENERATED_ROOT/{adapter} folder
  // shared by every project and every user, so one project's "Generate tests" run
  // could silently overwrite another's specs.
  const genRoot = process.env.TM_GENERATED_OUT_ROOT
    ? path.resolve(process.env.TM_GENERATED_OUT_ROOT)
    : path.join(GENERATED_ROOT, adapterId);

  if (!OPENAI_API_KEY) throw new Error("OPENAI_API_KEY missing");

  // Lightweight local path: skip GitHub integration, just generate tests and exit
  if (localMode) {
    await ensureStorageDirs();
    // Clear stale specs from a previous scan of this same project before writing
    // fresh ones, so a route that disappears (or is renamed) doesn't leave its old
    // spec file behind to be picked up and run against the new content.
    await fs.rm(genRoot, { recursive: true, force: true }).catch(() => {});
    await fs.mkdir(genRoot, { recursive: true });
    await fs.writeFile(path.join(genRoot, "README.md"), "# Generated by TestMind Agent\n", "utf8");
    const sharedSteps = parseSharedStepsEnv();

    await generateAndWrite({
      repoPath: process.cwd(),
      outRoot: path.resolve(genRoot),
      baseUrl: process.env.TEST_BASE_URL ?? "http://localhost:3000",
      adapterId,
      options: {
        maxRoutes: 25,
        sharedSteps,
      },
    });
    // Playwright execution is handled by startGeneratedRun (step 6) — don't run it here.
    return;
  }

  if (!GITHUB_REPOSITORY) throw new Error("GITHUB_REPOSITORY missing");
  if (!GITHUB_EVENT_PATH) throw new Error("GITHUB_EVENT_PATH missing");

  const [owner, repo] = GITHUB_REPOSITORY.split("/");
  const payload = JSON.parse(await fs.readFile(GITHUB_EVENT_PATH, "utf8"));
  const repoRef = { owner, repo };
  const octokit = await getOctokit();

  // Determine PR & command
  let prNumber: number | undefined;
  let userPrompt = "plan+gen+run";

  if (GITHUB_EVENT_NAME === "pull_request") {
    prNumber = payload.pull_request?.number;
  } else if (GITHUB_EVENT_NAME === "issue_comment") {
    const body: string = payload.comment?.body || "";
    if (!body.trim().startsWith("/testmind")) return; // ignore other comments
    prNumber = payload.issue?.number;
    userPrompt = body.replace("/testmind", "").trim() || userPrompt;
  }
  if (!prNumber) return;

  await comment(octokit, repoRef, prNumber, "🤖 TestMind Agent starting…");

  // Quick repo “scan”
  let fileCount = 0;
  try {
    const { stdout } = await exec("git ls-files | wc -l");
    fileCount = Number(stdout.trim()) || 0;
  } catch {
    // ignore
  }

  // Plan via OpenAI chat
  const openai = new OpenAI({ apiKey: OPENAI_API_KEY });
  const planMsg = await openai.chat.completions.create({
    model: "gpt-4o-mini",
    messages: [
      { role: "system", content: "You are TestMind. Produce a prioritized, concise E2E plan (routes + key flows) in markdown bullets." },
      { role: "user", content: `Repo has ~${fileCount} tracked files. Command: ${userPrompt}.` },
    ],
  });
  const plan = planMsg.choices[0]?.message?.content ?? "(no plan)";

  // Generate stub (replace with your generator hookup)
  await ensureStorageDirs();
  await fs.mkdir(genRoot, { recursive: true });
  await fs.writeFile(path.join(genRoot, "README.md"), "# Generated by TestMind Agent\n", "utf8");
  
  

await generateAndWrite({
  repoPath: process.cwd(),
  outRoot: path.resolve(genRoot),
  baseUrl: process.env.TEST_BASE_URL ?? "http://localhost:3000",
  adapterId,
  options: {
    maxRoutes: 25,        // << move it here
    // add other knobs if you have them, e.g. includeAuthFlows: true
    sharedSteps: parseSharedStepsEnv(),
  },
});


  

  // Run Playwright (if configured)
  let summary = "";
  try {
    await exec("pnpm playwright test --reporter=list");
    summary = "✅ All tests passed.";
  } catch {
    summary = "❌ Some tests failed. Check the report/artifacts.";
  }

  await comment(
    octokit,
    repoRef,
    prNumber,
    `### TestMind Agent Result\n${summary}\n\n**Plan:**\n${plan}`
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
