name: testmind-agent

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      target_pr:
        description: "PR number to run against (e.g., 1)"
        required: true
        type: string
      command:
        description: "Agent command"
        required: false
        default: "plan+gen+run"
        type: string

jobs:
  run-agent:
    if: >
      github.event_name == 'pull_request' ||
      (github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '/testmind')) ||
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # DO NOT set cache: 'pnpm' here; setup-node would try to run pnpm too early.
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # Enable pnpm via Corepack and activate a 9.x build (or read from package.json)
      - name: Enable Corepack (pnpm)
        run: |
          corepack enable
          # Use the version from package.json: "packageManager": "pnpm@x.y.z"
          VER=$(node -p "require('./package.json').packageManager?.split?.('@')[1] || ''")
          if [ -z "$VER" ]; then VER="latest-9"; fi
          corepack prepare "pnpm@${VER}" --activate
          pnpm -v

      - name: Install deps
        run: pnpm i --frozen-lockfile
        
      - name: Install Playwright browsers (and OS deps)
        uses: microsoft/playwright-github-action@v1

      # When manually run, synthesize an issue_comment payload for the runner
      - name: Prepare event payload (manual only)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo '{ "issue": { "number": '"${TARGET_PR}"' }, "comment": { "body": "/testmind '"${CMD}"'" } }' > event.json
          echo "GITHUB_EVENT_NAME=issue_comment" >> $GITHUB_ENV
          echo "GITHUB_EVENT_PATH=$GITHUB_WORKSPACE/event.json" >> $GITHUB_ENV
        env:
          TARGET_PR: ${{ inputs.target_pr }}
          CMD: ${{ inputs.command }}

      - name: Run TestMind Agent
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # Optional GitHub App creds (only if you use them)
          GITHUB_APP_ID: ${{ secrets.GITHUB_APP_ID }}
          GITHUB_APP_INSTALLATION_ID: ${{ secrets.GITHUB_APP_INSTALLATION_ID }}
          GITHUB_APP_PRIVATE_KEY_BASE64: ${{ secrets.GITHUB_APP_PRIVATE_KEY_BASE64 }}
          # Default Actions token for commenting/committing
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm tsx apps/api/src/runner/bot.ts

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore
